apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: harbor-redis
spec:
  sentinel:
    replicas: 3
    image: registry.suse.com/harbor/harbor-redis:2.1.0
    customConfig:
      - "dir /data"
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
    securityContext:
      fsGroup: 999
      runAsUser: 999
      runAsGroup: 999
  redis:
    replicas: 3
    image: registry.suse.com/harbor/harbor-redis:2.1.0
    customConfig:
      - "dir /data"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
    securityContext:
      fsGroup: 999
      runAsUser: 999
      runAsGroup: 999
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: harbor-redis-data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  auth:
    secretPath: redis-auth
